"""
Recommendation Engine Schemas
=============================
Defines Pydantic schemas for project team candidate recommendations,
factual explainability signals, and ranking results.
"""

from typing import List, Optional
from uuid import UUID
from pydantic import BaseModel, Field


class MatchedSkillInfo(BaseModel):
    """Factual detail of a project required skill possessed by the student."""
    skill_id: str = Field(..., description="Master taxonomy skill ID")
    skill_name: str = Field(..., description="Canonical skill name")
    student_proficiency: int = Field(..., ge=1, le=4, description="Student's self-assessed proficiency level (1-4)")
    required_proficiency: int = Field(..., ge=1, le=4, description="Project's required proficiency level (1-4)")
    category: Optional[str] = Field(None, description="Skill domain category (e.g., ai_ml, backend)")


class MissingSkillInfo(BaseModel):
    """Factual detail of a project required skill missing from the student's profile."""
    skill_id: str = Field(..., description="Master taxonomy skill ID")
    skill_name: str = Field(..., description="Canonical skill name")
    required_proficiency: int = Field(..., ge=1, le=4, description="Project's required proficiency level (1-4)")
    category: Optional[str] = Field(None, description="Skill domain category")


class FactualExplanation(BaseModel):
    """
    Factual evidence breakdown explaining model compatibility score.
    Does not use speculative or exaggerated subjective natural language.
    """
    matched_skills: List[MatchedSkillInfo] = Field(
        default_factory=list,
        description="Required skills that the student possesses",
    )
    missing_skills: List[MissingSkillInfo] = Field(
        default_factory=list,
        description="Required skills that the student has not yet declared",
    )
    skill_coverage_ratio: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Ratio of required project skills possessed by student",
    )
    proficiency_alignment: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized metric indicating how closely student meets or exceeds required proficiency (1.0 - deficit)",
    )
    interest_overlap: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Domain interest overlap between student and project",
    )
    experience_signal: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized previous project experience signal",
    )


class StudentRecommendation(BaseModel):
    """A single ranked candidate student recommendation for a project."""
    rank: int = Field(..., ge=1, description="Rank ordered by compatibility score descending (1 = highest)")
    student_id: UUID = Field(..., description="Candidate student ID")
    student_name: str = Field(..., description="Candidate student full name")
    academic_year: Optional[int] = Field(None, ge=1, le=5, description="Academic year (1-5)")
    compatibility_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Continuous compatibility score [0.0, 1.0] generated by trained PyTorch MLP",
    )
    matched_skill_count: int = Field(..., ge=0, description="Count of project required skills matched")
    required_skill_count: int = Field(..., ge=0, description="Total project required skills count")
    skill_coverage_ratio: float = Field(..., ge=0.0, le=1.0)
    mean_proficiency_matched: float = Field(..., ge=0.0, le=1.0)
    proficiency_deficit_ratio: float = Field(..., ge=0.0, le=1.0)
    interest_domain_overlap: float = Field(..., ge=0.0, le=1.0)
    prior_project_experience_norm: float = Field(..., ge=0.0, le=1.0)
    certification_count_norm: float = Field(..., ge=0.0, le=1.0)
    explanation: FactualExplanation = Field(..., description="Factual evidence breakdown")
    invitation_status: Optional[str] = Field(None, description="Current invitation status: pending, accepted, rejected, cancelled, or None")
    invitation_id: Optional[UUID] = Field(None, description="UUID of the invitation if one exists")


class ProjectRecommendationResponse(BaseModel):
    """Top-K candidate recommendation response for an authenticated project."""
    project_id: UUID = Field(..., description="Target project UUID")
    project_title: str = Field(..., description="Project title")
    total_eligible_candidates: int = Field(..., ge=0, description="Total candidate students evaluated after filtering")
    returned_recommendations_count: int = Field(..., ge=0, description="Count of recommendations returned in Top-K")
    min_score_threshold: float = Field(..., ge=0.0, le=1.0, description="Minimum compatibility score threshold applied")
    model_version: str = Field(..., description="PyTorch MLP model checkpoint version used")
    recommendations: List[StudentRecommendation] = Field(
        default_factory=list,
        description="Rank-ordered list of candidate recommendations",
    )
